package com.shelke.sachin.cruddemo.entity;

import jakarta.persistence.*;

@Entity
@Table(name = "student") // mapping to db table student (also, optional - will take class name)
public class Student {

    //define fields
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Mysql will handle the id generation
    @Column(name = "id")
    private int id;

    @Column(name = "first_name") // mapping to db column (also, optional - will take variable name)
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "email")
    private String email;

    //define constructors
    public Student() {
    }

    public Student(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        //id will be generated by Db
    }

    //generate getter and setter
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    //define toString() method

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                ", firstName=" + firstName +
                ", lastName=" + lastName +
                ", email=" + email +
                '}';
    }
}
